# Generated by Django 5.2.18 on 2026-10-08 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('office_type', models.CharField(choices=[('REGIONAL', 'Regional Office'), ('PROVINCIAL', 'Provincial Office'), ('FIELD', 'Field Office'), ('SATELLITE', 'Satellite Office')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.office')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='offices',
            field=models.ManyToManyField(blank=True, help_text='Offices whose records this user may access.', related_name='users', to='accounts.office'),
        ),
    ]
