# Generated by Django 5.2.18 on 2026-10-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_office_user_offices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['code'], 'permissions': [('view_all_offices', 'Can access records of all offices')]},
        ),
    ]
