# Generated by Django 5.2.18 on 2026-10-08 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DOCUMENT_EXPIRY', 'Document expiration'), ('LTO_RENEWAL', 'LTO renewal'), ('INSURANCE_EXPIRY', 'GSIS/insurance expiration'), ('LICENSE_EXPIRY', 'Driver license expiration'), ('MAINTENANCE_DUE', 'Maintenance due'), ('MAINTENANCE_OVERDUE', 'Maintenance overdue'), ('ASSIGNMENT', 'Assignment')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='uniq_notification_per_event')],
            },
        ),
    ]
