# Generated by Django 5.2.18 on 2026-10-08 01:13

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_office_user_offices'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('EASYTRIP', 'Easytrip'), ('AUTOSWEEP', 'Autosweep'), ('OTHER', 'Other')], max_length=20)),
                ('account_number', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Manually recorded balance.', max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfid_accounts', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=40, unique=True)),
                ('passengers', models.TextField(blank=True)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('departed_at', models.DateTimeField(db_index=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('odometer_start', models.IntegerField()),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('odometer_end'), '-', models.F('odometer_start')), output_field=models.IntegerField(null=True))),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DISPATCHED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driver')),
                ('requesting_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.office')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-departed_at'],
            },
        ),
        migrations.CreateModel(
            name='TollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transacted_at', models.DateTimeField(db_index=True)),
                ('description', models.CharField(help_text='Toll plaza / load / adjustment', max_length=200)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='operations.rfidaccount')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toll_transactions', to='fleet.vehicle')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toll_transactions', to='operations.trip')),
            ],
            options={
                'ordering': ['-transacted_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('po_number', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='PO number')),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('OTHER', 'Other')], max_length=20)),
                ('liters', models.DecimalField(decimal_places=3, max_digits=9)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='As printed on the receipt.', max_digits=12)),
                ('odometer', models.IntegerField()),
                ('is_full_tank', models.BooleanField(default=False, help_text='Only full-tank fill-ups give a fair km/L estimate.')),
                ('receipt_number', models.CharField(blank=True, max_length=40)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date', '-odometer'],
                'indexes': [models.Index(fields=['vehicle', 'date'], name='operations__vehicle_d59283_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('liters__gte', 0)), name='operations_fuelrecord_liters_gte_0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='operations_fuelrecord_unit_price_gte_0'), models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='operations_fuelrecord_total_amount_gte_0'), models.CheckConstraint(condition=models.Q(('odometer__gte', 0)), name='operations_fuelrecord_odometer_gte_0')],
            },
        ),
        migrations.AddConstraint(
            model_name='rfidaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'account_number'), name='uniq_rfid_account'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('odometer_start__gte', 0)), name='operations_trip_odometer_start_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('odometer_end__isnull', True), ('odometer_end__gte', models.F('odometer_start')), _connector='OR'), name='operations_trip_odometer_end_after_odometer_start'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('departed_at')), _connector='OR'), name='operations_trip_returned_at_after_departed_at'),
        ),
        migrations.AddConstraint(
            model_name='tolltransaction',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='operations_tolltransaction_credit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tolltransaction',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='operations_tolltransaction_debit_gte_0'),
        ),
    ]
