# Generated by Django 5.2.18 on 2026-10-08 01:13

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'maintenance categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=40, verbose_name='PR / reference number')),
                ('description', models.TextField()),
                ('service_provider', models.CharField(blank=True, max_length=150)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('labor_cost'), '+', models.F('parts_cost')), output_field=models.DecimalField(decimal_places=2, max_digits=13))),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('FOR_INSPECTION', 'For Inspection'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_odometer', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(related_name='records', to='maintenance.maintenancecategory')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('odometer__gte', 0)), name='maintenance_maintenancerecord_odometer_gte_0'), models.CheckConstraint(condition=models.Q(('labor_cost__gte', 0)), name='maintenance_maintenancerecord_labor_cost_gte_0'), models.CheckConstraint(condition=models.Q(('parts_cost__gte', 0)), name='maintenance_maintenancerecord_parts_cost_gte_0'), models.CheckConstraint(condition=models.Q(('completed_on__isnull', True), ('completed_on__gte', models.F('started_on')), _connector='OR'), name='maintenance_maintenancerecord_completed_on_after_started_on')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_odometer', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='maintenance.maintenancecategory')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='fleet.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'category'), name='uniq_schedule_vehicle_category'), models.CheckConstraint(condition=models.Q(('interval_days__isnull', False), ('interval_km__isnull', False), _connector='OR'), name='schedule_has_interval')],
            },
        ),
    ]
