# Generated by Django 5.2.18 on 2026-10-08 01:13

import config.base_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_office_user_offices'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('license_type', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('NON_PROFESSIONAL', 'Non-Professional')], max_length=20)),
                ('license_restrictions', models.CharField(blank=True, help_text='e.g. A, B, B1, B2', max_length=50)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='accounts.office')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('property_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('year_model', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'Van'), ('PICKUP', 'Pickup'), ('BUS', 'Bus'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('OTHER', 'Other')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Electric'), ('OTHER', 'Other')], max_length=20)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_odometer', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SERVICEABLE', 'Serviceable'), ('IN_USE', 'In Use'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('FOR_REPAIR', 'For Repair'), ('UNSERVICEABLE', 'Unserviceable'), ('DISPOSED', 'Disposed')], db_index=True, default='SERVICEABLE', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=config.base_models.safe_upload_to)),
                ('remarks', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(help_text='Owning office; drives office-level access scoping.', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='accounts.office')),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountable_person', models.CharField(help_text='Name as of assignment (historical snapshot).', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.office')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('LTO_REGISTRATION', 'LTO Registration'), ('OR', 'Official Receipt'), ('CR', 'Certificate of Registration'), ('GSIS_INSURANCE', 'GSIS Insurance'), ('INSURANCE_POLICY', 'Insurance Policy'), ('DEED', 'Deed / Property Record'), ('INSPECTION', 'Inspection Record'), ('OTHER', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=60)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=config.base_models.safe_upload_to)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(upload_to=config.base_models.safe_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='fleet_attac_content_373a65_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(condition=models.Q(('license_expiry_date__isnull', True), ('license_expiry_date__gte', models.F('license_issue_date')), _connector='OR'), name='fleet_driver_license_expiry_date_after_license_issue_date'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('current_odometer__gte', 0)), name='fleet_vehicle_current_odometer_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('acquisition_cost__gte', 0)), name='fleet_vehicle_acquisition_cost_gte_0'),
        ),
        migrations.AddIndex(
            model_name='vehicleassignment',
            index=models.Index(fields=['vehicle', 'end_date'], name='fleet_vehic_vehicle_7eca61_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='fleet_vehicleassignment_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='vehicledocument',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('expiry_date__gte', models.F('issue_date')), _connector='OR'), name='fleet_vehicledocument_expiry_date_after_issue_date'),
        ),
    ]
