# Generated by Django 5.2.18 on 2026-10-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate_number'], 'permissions': [('manage_vehicle_photo', 'Can upload, replace and remove vehicle photos'), ('correct_odometer', 'Can lower a vehicle odometer (authorized correction)')]},
        ),
    ]
