# Generated by Django 5.2.18 on 2026-10-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Driver name as of assignment (historical snapshot).', max_length=150),
        ),
    ]
