# Generated by Django 5.2.18 on 2026-10-08 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Snapshot; survives user rename/deletion.', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, help_text='create / update / archive / delete / login ...', max_length=30)),
                ('entity_type', models.CharField(db_index=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": [old, new]}')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
